#==================================================
# secret for docker registry
#==================================================
apiVersion: apps/v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>

---
#==================================================
# secret for application
#==================================================
apiVersion: apps/v1
kind: Secret
metadata:
  name: secret
  namespace: default
type: Opaque
data:
  jasypt_encryptor_password: <password>

