#==================================================
# argocd
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: argocd
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local

---
#==================================================
# prometheus
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ExternalName
  externalName: prometheus-server.prometheus.svc.cluster.local


