#==================================================
# ip_192_168_0_2
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: ip-192-168-0-2
spec:
  type: ExternalName
  externalName: 192.168.0.2

---
#==================================================
# argocd
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: argocd
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local

---
#==================================================
# prometheus
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ExternalName
  externalName: prometheus-server.prometheus.svc.cluster.local


