#==================================================
# nfs pv
#==================================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.2
    path: /home/chomookun/nfs
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: nfs
    namespace: default

---
#==================================================
# nfs pvc
#==================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


