apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  #annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: jenkins.oopscraft.org
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jenkins
                port:
                  number: 9999
    - host: argocd.oopscraft.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: argocd
                port:
                  number: 80
    - host: apps-web.oopscraft.org
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: apps-web
                port:
                  number: 8080
