#==================================================
# apps-web deployment
#==================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-web
spec:
  selector:
    matchLabels:
      app: apps-web
  replicas: 2
  template:
    metadata:
      labels:
        app: apps-web
    spec:
      imagePullSecrets:
        - name: docker-public
      containers:
        - name: apps-web
          image: 192.168.0.2:9997/oopscraft/apps-web:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: JAVA_TOOL_OPTIONS
              value: |
                -Dfile.encoding=UTF-8
                -javaagent:/nfs/scouter/agent.java/scouter.agent.jar
                -Dobj_name=apps-web
          volumeMounts:
            - mountPath: /nfs
              name: nfs
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs


---
#==================================================
# apps-web service
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: apps-web
spec:
  type: LoadBalancer
  selector:
    app: apps-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
