#==================================================
# arch4j-web deployment
#==================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arch4j-web
  namespace: default
spec:
  selector:
    matchLabels:
      app: arch4j-web
  replicas: 2
  template:
    metadata:
      labels:
        app: arch4j-web
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - name: arch4j-web
          image: 192.168.0.2:9997/oopscraft/arch4j-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: LOGGING_LEVEL_ROOT
              value: INFO
            - name: JAVA_TOOL_OPTIONS
              value: |
                -Dfile.encoding=UTF-8
#                -javaagent:/scouter/agent.java/scouter.agent.jar
#          volumeMounts:
#            - mountPath: /scouter
#              name: scouter
#      volumes:
#        - name: scouter
#          persistentVolumeClaim:
#            claimName: scouter

---
#==================================================
# arch4j-web service
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: arch4j-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  type: LoadBalancer
  selector:
    app: arch4j-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
