#==================================================
# fintics deployment
#==================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintics-web
  namespace: default
spec:
  selector:
    matchLabels:
      app: fintics-web
  replicas: 1
  template:
    metadata:
      labels:
        app: fintics-web
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - name: fintics
          image: 192.168.0.2:9997/chomookun/fintics:latest
          args: []
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          env:
            - name: TZ
              value: Asia/Seoul
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: jasypt_encryptor_password
            - name: JAVA_TOOL_OPTIONS
              value: |
                -Dfile.encoding=UTF-8
                -Dnetworkaddress.cache.ttl=1
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-data

---
#==================================================
# fintics service
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: fintics-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  type: LoadBalancer
  selector:
    app: fintics-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
