apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-web
spec:
  selector:
    matchLabels:
      app: apps-web
  replicas: 2
  template:
    metadata:
      labels:
        app: apps-web
    spec:
      containers:
        - name: apps-web
          image: 971936428072.dkr.ecr.ap-northeast-2.amazonaws.com/apps-web:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
      imagePullSecrets:
        - name: docker-public

---
apiVersion: v1
kind: Service
metadata:
  name: apps-web
spec:
  type: LoadBalancer
  selector:
    app: apps-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
