#==================================================
# duice-site deployment
#==================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duice-site
  namespace: default
spec:
  selector:
    matchLabels:
      app: duice-site
  replicas: 1
  template:
    metadata:
      labels:
        app: duice-site
    spec:
      imagePullSecrets:
        - name: docker-credentials
      containers:
        - name: duice-site
          image: 192.168.0.2:9997/oopscraft/duice-site:latest
          args: []
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          env:
            - name: TZ
              value: Asia/Seoul
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-data

---
#==================================================
# duice-site service
#==================================================
apiVersion: v1
kind: Service
metadata:
  name: duice-site
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: duice-site
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
